#### 1. Importing the dependencies

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
import tensorflow as tf
print(tf.__version__)

2.11.0


#### 2. Text Preprocessing:
In this step, we are going to convert these sentences into vectors.


In [9]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [10]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [18]:
#### Vocabulary Size:
voc_size=500

In [19]:
# One Hot Representation
onehot_repr=[one_hot(words,voc_size) for words in sent]

In [20]:
onehot_repr
# that returns the index number of each word

[[4, 131, 216, 368],
 [4, 131, 216, 247],
 [4, 74, 216, 169],
 [241, 476, 487, 486, 445],
 [241, 476, 487, 486, 30],
 [219, 4, 422, 216, 471],
 [374, 339, 229, 486]]

#### Word Embedding Representation:

Pre padding and post padding: that is used to ensure that all of the sentences are of equal size before they are forwarded to the neural network.

In [21]:
# importing the dependencies:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [24]:
#pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0   4 131 216 368]
 [  0   0   0   0   4 131 216 247]
 [  0   0   0   0   4  74 216 169]
 [  0   0   0 241 476 487 486 445]
 [  0   0   0 241 476 487 486  30]
 [  0   0   0 219   4 422 216 471]
 [  0   0   0   0 374 339 229 486]]


In [ ]:
# feature dimension representation
dim=10
# here each index will be represented with 10 different values

In [25]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [26]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [28]:
# The vector represenation of the sentence 'The glass of milk'
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 24ms/step


array([[ 0.02806805,  0.00826656,  0.03500443,  0.01711503,  0.03020241,
         0.01168672, -0.02638896, -0.02245723,  0.01033088, -0.0444128 ],
       [ 0.02806805,  0.00826656,  0.03500443,  0.01711503,  0.03020241,
         0.01168672, -0.02638896, -0.02245723,  0.01033088, -0.0444128 ],
       [ 0.02806805,  0.00826656,  0.03500443,  0.01711503,  0.03020241,
         0.01168672, -0.02638896, -0.02245723,  0.01033088, -0.0444128 ],
       [ 0.02806805,  0.00826656,  0.03500443,  0.01711503,  0.03020241,
         0.01168672, -0.02638896, -0.02245723,  0.01033088, -0.0444128 ],
       [ 0.03712735, -0.04317545,  0.03117067, -0.0233558 ,  0.04059   ,
         0.04080827, -0.03113912, -0.01265422, -0.03483198, -0.0157162 ],
       [-0.0137173 , -0.02348101, -0.04084193, -0.01727998,  0.0310442 ,
         0.00446476,  0.01044506, -0.03110282, -0.01764943,  0.01695393],
       [ 0.01760134,  0.02674446,  0.00206999, -0.016236  ,  0.01392527,
        -0.02685583, -0.00972946, -0.00014894

In [29]:
model.predict(embedded_docs[1])

1/1 [==============================] - 0s 28ms/step


array([[ 0.02806805,  0.00826656,  0.03500443,  0.01711503,  0.03020241,
         0.01168672, -0.02638896, -0.02245723,  0.01033088, -0.0444128 ],
       [ 0.02806805,  0.00826656,  0.03500443,  0.01711503,  0.03020241,
         0.01168672, -0.02638896, -0.02245723,  0.01033088, -0.0444128 ],
       [ 0.02806805,  0.00826656,  0.03500443,  0.01711503,  0.03020241,
         0.01168672, -0.02638896, -0.02245723,  0.01033088, -0.0444128 ],
       [ 0.02806805,  0.00826656,  0.03500443,  0.01711503,  0.03020241,
         0.01168672, -0.02638896, -0.02245723,  0.01033088, -0.0444128 ],
       [ 0.03712735, -0.04317545,  0.03117067, -0.0233558 ,  0.04059   ,
         0.04080827, -0.03113912, -0.01265422, -0.03483198, -0.0157162 ],
       [-0.0137173 , -0.02348101, -0.04084193, -0.01727998,  0.0310442 ,
         0.00446476,  0.01044506, -0.03110282, -0.01764943,  0.01695393],
       [ 0.01760134,  0.02674446,  0.00206999, -0.016236  ,  0.01392527,
        -0.02685583, -0.00972946, -0.00014894

In [30]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 45ms/step


array([[[ 0.02806805,  0.00826656,  0.03500443,  0.01711503,
          0.03020241,  0.01168672, -0.02638896, -0.02245723,
          0.01033088, -0.0444128 ],
        [ 0.02806805,  0.00826656,  0.03500443,  0.01711503,
          0.03020241,  0.01168672, -0.02638896, -0.02245723,
          0.01033088, -0.0444128 ],
        [ 0.02806805,  0.00826656,  0.03500443,  0.01711503,
          0.03020241,  0.01168672, -0.02638896, -0.02245723,
          0.01033088, -0.0444128 ],
        [ 0.02806805,  0.00826656,  0.03500443,  0.01711503,
          0.03020241,  0.01168672, -0.02638896, -0.02245723,
          0.01033088, -0.0444128 ],
        [ 0.03712735, -0.04317545,  0.03117067, -0.0233558 ,
          0.04059   ,  0.04080827, -0.03113912, -0.01265422,
         -0.03483198, -0.0157162 ],
        [-0.0137173 , -0.02348101, -0.04084193, -0.01727998,
          0.0310442 ,  0.00446476,  0.01044506, -0.03110282,
         -0.01764943,  0.01695393],
        [ 0.01760134,  0.02674446,  0.00206999, -0.0